apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes-api
  template:
    metadata:
      labels:
        app: notes-api
    spec:
      containers:
      - name: notes-api
        image: fhsinchy/notes-api
        resources:
        ports:
        - containerPort: 3000
        env:
        - name: DB_CONNECTION
          value: pg
        - name: DB_HOST
          value: notes-db-service
        - name: DB_PORT
          value: '5432'
        - name: DB_USER
          value: postgres
        - name: DB_DATABASE
          value: notesdb
        - name: DB_PASSWORD
          value: 63eaQB9wtLqmNBpg
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5
